.TH DOCKY "1"
.SH NAME
Docky \- a full fledged dock application that makes opening common applications and managing windows easier and quicker. Docky is fully integrated into the GNOME Desktop and features a no non-sense approach to configuration and usage. It just works.
.SH SYNOPSIS
docky [\fIoptions\fR]
.SH OPTIONS
.TP
\fB\-p\fR \fB\-\-disable\-polling\fR
Disable cursor polling (for testing)
.TP
\fB\-m\fR \fB\-\-max\-size\fR=\fR\fIsize\fR
Maximum window dimension (min 500)
.TP
\fB\-b\fR \fB\-\-buffer\-time\fR=\fR\fItime\fR
Maximum time (in minutes) to keep buffers
.TP
\fB\-n\fR \fB\-\-netbook\fR
Netbook mode
.TP
\fB\-\-nvidia\fR
Nvidia mode (for Nvidia cards that lag after awhile) [\-b 10]
.TP
\fB\-d\fR \fB\-\-debug\fR
Enable debug level logging
.TP
\fB\-?\fR \fB\-\-help\fR
Show this help list
.SH HOMEPAGE
For more information, please visit http://launchpad.net/docky/
.SH AUTHORS
Jason Smith <jassmith@gmail.com>, Robert Dyer <psybers@gmail.com>, Chris Szikszoy <chris@szikszoy.com>, Daniel Foré <daniel.p.fore@gmail.com>, Rico Tzschichholz <ricotz@t-online.de>
