
// This file has been generated by the GUI designer. Do not modify.
namespace GMail
{
	public partial class GMailLabelConfig
	{
		private global::Gtk.VBox vbox1;
		private global::Gtk.HBox hbox1;
		private global::Docky.Widgets.SearchEntry label_entry;
		private global::Gtk.Button add_label;
		private global::Gtk.ScrolledWindow scrolledwindow1;
		private global::Docky.Widgets.ListOnlyTileView label_list;
		private global::Gtk.HBox hbox2;
		private global::Gtk.Label label1;
		private global::Gtk.Label label2;
		private global::Gtk.SpinButton check_interval;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget GMail.GMailLabelConfig
			global::Stetic.BinContainer.Attach (this);
			this.Name = "GMail.GMailLabelConfig";
			// Container child GMail.GMailLabelConfig.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label_entry = new global::Docky.Widgets.SearchEntry ();
			this.label_entry.Name = "label_entry";
			this.label_entry.EmptyMessage = "Label Name";
			this.label_entry.Query = "";
			this.label_entry.Ready = true;
			this.label_entry.HasFocus = false;
			this.hbox1.Add (this.label_entry);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label_entry]));
			w1.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.add_label = new global::Gtk.Button ();
			this.add_label.CanFocus = true;
			this.add_label.Name = "add_label";
			this.add_label.UseUnderline = true;
			// Container child add_label.Gtk.Container+ContainerChild
			global::Gtk.Alignment w2 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w3 = new global::Gtk.HBox ();
			w3.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w4 = new global::Gtk.Image ();
			w4.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.Menu);
			w3.Add (w4);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w6 = new global::Gtk.Label ();
			w6.LabelProp = global::Mono.Unix.Catalog.GetString ("_Add Label");
			w6.UseUnderline = true;
			w3.Add (w6);
			w2.Add (w3);
			this.add_label.Add (w2);
			this.hbox1.Add (this.add_label);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.add_label]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.scrolledwindow1 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow1.CanFocus = true;
			this.scrolledwindow1.Name = "scrolledwindow1";
			this.scrolledwindow1.HscrollbarPolicy = ((global::Gtk.PolicyType)(2));
			this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow1.Gtk.Container+ContainerChild
			global::Gtk.Viewport w12 = new global::Gtk.Viewport ();
			w12.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.label_list = new global::Docky.Widgets.ListOnlyTileView ();
			this.label_list.Name = "label_list";
			this.label_list.IconSize = 0;
			w12.Add (this.label_list);
			this.scrolledwindow1.Add (w12);
			this.vbox1.Add (this.scrolledwindow1);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.scrolledwindow1]));
			w15.Position = 1;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Check e_very:");
			this.label1.UseUnderline = true;
			this.hbox2.Add (this.label1);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label1]));
			w16.Position = 0;
			w16.Expand = false;
			w16.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("minutes");
			this.hbox2.Add (this.label2);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label2]));
			w17.PackType = ((global::Gtk.PackType)(1));
			w17.Position = 1;
			w17.Expand = false;
			w17.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.check_interval = new global::Gtk.SpinButton (2, 1440, 1);
			this.check_interval.CanFocus = true;
			this.check_interval.Name = "check_interval";
			this.check_interval.Adjustment.PageIncrement = 10;
			this.check_interval.ClimbRate = 1;
			this.check_interval.Numeric = true;
			this.check_interval.Value = 15;
			this.hbox2.Add (this.check_interval);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.check_interval]));
			w18.PackType = ((global::Gtk.PackType)(1));
			w18.Position = 2;
			w18.Expand = false;
			w18.Fill = false;
			this.vbox1.Add (this.hbox2);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
			w19.Position = 2;
			w19.Expand = false;
			w19.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.label1.MnemonicWidget = this.check_interval;
			this.Hide ();
			this.add_label.Clicked += new global::System.EventHandler (this.AddLabelClicked);
			this.check_interval.ValueChanged += new global::System.EventHandler (this.OnIntervalValueChanged);
		}
	}
}
