
// This file has been generated by the GUI designer. Do not modify.
namespace WeatherDocklet
{
	public partial class WeatherConfig
	{
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.ComboBox provider;
		
		private global::Docky.Widgets.WrapLabel provider_info;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.Button my_locations;
		
		private global::Docky.Widgets.SearchEntry location_code;
		
		private global::Gtk.Button search;
		
		private global::Gtk.ScrolledWindow scrolledwindow1;
		
		private global::Docky.Widgets.TileView results_view;
		
		private global::Gtk.HBox hbox3;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.Label label3;
		
		private global::Gtk.SpinButton auto_update;
		
		private global::Gtk.HBox hbox4;
		
		private global::Gtk.CheckButton metric_units;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget WeatherDocklet.WeatherConfig
			global::Stetic.BinContainer.Attach (this);
			this.Name = "WeatherDocklet.WeatherConfig";
			// Container child WeatherDocklet.WeatherConfig.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("_Weather Provider:");
			this.label1.UseUnderline = true;
			this.hbox1.Add (this.label1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.provider = global::Gtk.ComboBox.NewText ();
			this.provider.Name = "provider";
			this.hbox1.Add (this.provider);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.provider]));
			w2.PackType = ((global::Gtk.PackType)(1));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.provider_info = new global::Docky.Widgets.WrapLabel ();
			this.provider_info.Events = ((global::Gdk.EventMask)(256));
			this.provider_info.Name = "provider_info";
			this.provider_info.Wrap = false;
			this.vbox1.Add (this.provider_info);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.provider_info]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.my_locations = new global::Gtk.Button ();
			this.my_locations.CanFocus = true;
			this.my_locations.Name = "my_locations";
			this.my_locations.UseUnderline = true;
			this.my_locations.Label = global::Mono.Unix.Catalog.GetString ("My _Locations");
			this.hbox2.Add (this.my_locations);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.my_locations]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.location_code = new global::Docky.Widgets.SearchEntry ();
			this.location_code.Name = "location_code";
			this.location_code.EmptyMessage = "Location Code, Zip, or City";
			this.location_code.Ready = true;
			this.location_code.HasFocus = false;
			this.hbox2.Add (this.location_code);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.location_code]));
			w6.Position = 1;
			// Container child hbox2.Gtk.Box+BoxChild
			this.search = new global::Gtk.Button ();
			this.search.CanFocus = true;
			this.search.Name = "search";
			this.search.UseUnderline = true;
			this.search.Label = global::Mono.Unix.Catalog.GetString ("_Search");
			global::Gtk.Image w7 = new global::Gtk.Image ();
			w7.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-find", global::Gtk.IconSize.Menu);
			this.search.Image = w7;
			this.hbox2.Add (this.search);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.search]));
			w8.Position = 2;
			w8.Expand = false;
			w8.Fill = false;
			this.vbox1.Add (this.hbox2);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
			w9.Position = 2;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.scrolledwindow1 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow1.CanFocus = true;
			this.scrolledwindow1.Name = "scrolledwindow1";
			this.scrolledwindow1.HscrollbarPolicy = ((global::Gtk.PolicyType)(2));
			this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow1.Gtk.Container+ContainerChild
			global::Gtk.Viewport w10 = new global::Gtk.Viewport ();
			w10.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.results_view = new global::Docky.Widgets.TileView ();
			this.results_view.Name = "results_view";
			this.results_view.IconSize = 24;
			w10.Add (this.results_view);
			this.scrolledwindow1.Add (w10);
			this.vbox1.Add (this.scrolledwindow1);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.scrolledwindow1]));
			w13.Position = 3;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Automatically Update _Every");
			this.label2.UseUnderline = true;
			this.hbox3.Add (this.label2);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label2]));
			w14.Position = 0;
			w14.Expand = false;
			w14.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("minutes");
			this.hbox3.Add (this.label3);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label3]));
			w15.PackType = ((global::Gtk.PackType)(1));
			w15.Position = 1;
			w15.Expand = false;
			w15.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.auto_update = new global::Gtk.SpinButton (5, 60, 5);
			this.auto_update.CanFocus = true;
			this.auto_update.Name = "auto_update";
			this.auto_update.Adjustment.PageIncrement = 10;
			this.auto_update.ClimbRate = 1;
			this.auto_update.Numeric = true;
			this.auto_update.Value = 5;
			this.hbox3.Add (this.auto_update);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.auto_update]));
			w16.PackType = ((global::Gtk.PackType)(1));
			w16.Position = 2;
			w16.Expand = false;
			w16.Fill = false;
			this.vbox1.Add (this.hbox3);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox3]));
			w17.Position = 4;
			w17.Expand = false;
			w17.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.metric_units = new global::Gtk.CheckButton ();
			this.metric_units.CanFocus = true;
			this.metric_units.Name = "metric_units";
			this.metric_units.Label = global::Mono.Unix.Catalog.GetString ("Use _Metric Units");
			this.metric_units.Active = true;
			this.metric_units.DrawIndicator = true;
			this.metric_units.UseUnderline = true;
			this.hbox4.Add (this.metric_units);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.metric_units]));
			w18.Position = 0;
			this.vbox1.Add (this.hbox4);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox4]));
			w19.Position = 5;
			w19.Expand = false;
			w19.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.label1.MnemonicWidget = this.provider;
			this.Hide ();
			this.provider.Changed += new global::System.EventHandler (this.OnProviderChanged);
			this.my_locations.Clicked += new global::System.EventHandler (this.OnMyLocationsClicked);
			this.search.Clicked += new global::System.EventHandler (this.OnSearchClicked);
			this.auto_update.ValueChanged += new global::System.EventHandler (this.OnUpdateValueChanged);
			this.metric_units.Toggled += new global::System.EventHandler (this.OnMetricToggled);
		}
	}
}
